# Security configuration for PC Control MCP Server

# Authentication settings
authentication:
  methods:
    - none      # No authentication (development only)
    - basic     # Basic username/password
    - token     # Token-based authentication
  token:
    algorithm: "HS256"
    expiry_seconds: 3600
    refresh_enabled: true
    refresh_expiry_seconds: 86400

# Authorization rules
authorization:
  default_policy: "deny"  # deny or allow
  rules:
    - resource: "system_info"
      actions: ["read"]
      allow: true
    - resource: "process_management"
      actions: ["read", "write", "delete"]
      allow: true
      conditions:
        - type: "process_whitelist"
          value: ["notepad.exe", "calculator.exe"]
    - resource: "file_operations"
      actions: ["read", "write", "delete"]
      allow: true
      conditions:
        - type: "path_whitelist"
          value: ["~/Documents", "~/Downloads"]
    - resource: "network_operations"
      actions: ["read"]
      allow: true
    - resource: "gui_automation"
      actions: ["read", "write"]
      allow: true
      conditions:
        - type: "safe_mode"
          value: true

# Input validation rules
validation:
  command_execution:
    max_length: 1000
    allowed_characters: "a-zA-Z0-9\\s\\-_./\\\\:\"'=,"
    blocked_patterns:
      - "rm -rf /"
      - "format c:"
      - "del /f /s /q"
  file_paths:
    max_length: 260
    must_be_absolute: false
    traversal_check: true
  process_names:
    max_length: 255
    allowed_characters: "a-zA-Z0-9\\-_."

# Audit logging
audit:
  enabled: true
  log_level: "INFO"
  log_format: "json"
  include_fields:
    - timestamp
    - user_id
    - action
    - resource
    - result
    - ip_address
    - user_agent
  sensitive_data_masking: true
  retention:
    days: 30
    max_size_mb: 1000

# Rate limiting
rate_limiting:
  enabled: true
  rules:
    - resource: "*"
      limit: 100
      window_seconds: 60
    - resource: "command_execution"
      limit: 10
      window_seconds: 60
    - resource: "file_operations"
      limit: 50
      window_seconds: 60

# Encryption settings
encryption:
  enabled: true
  algorithm: "AES-256-GCM"
  key_derivation: "PBKDF2"
  iterations: 100000
  sensitive_fields:
    - password
    - token
    - api_key
    - secret